project:
  type: manuscript

manuscript:
  article: index.qmd

execute:
  freeze: true

format:
  arxiv-pdf:
    toc: False
    toc-depth: 3
    number-sections: true
    keep-tex: true
    linenumbers: false # Add (continuous) line numbers?
    doublespacing: false # Double space the PDF output?
    runninghead: "Preprint" # The text on the top of each page of the output
    authorcols: true # Should authors be listed in a single column (default) or in multiple columns (`authorcols: true`)
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default